print("variables -----------")
print("snake_case")
print("start with lowercase or underscore")
print("letters, numbers, underscores")
print("case sensitive")
print("don't overwrite keywords")

user_iq = 190
print(user_iq)
user_age = user_iq / 4
a = user_age
print(a)

print("     ")
print("keywords -----------")
print("print")
print("and")
print("as")
print("assert")
print("break")
print("class")
print("continue")
print("def")
print("del")
print("elif")
print("else")
print("except")
print("finally")
print("for")
print("from")
print("global")
print("if")
print("import")
print("in")
print("is")
print("lambda")
print("nonlocal")
print("not")
print("or")
print("pass")
print("raise")
print("return")
print("try")
print("while")
print("with")
print("yield")


print("     ")
print("constant variables -----------")
print("PI = 3.14")
print("GRAVITY = 9.8")
print("SPEED_OF_LIGHT = 299792458")


print("     ")
print("Dunder variables -----------")
print("__init__")
print("__str__")
print("__repr__")
print("__len__")
print("__getitem__")
print("__setitem__")
print("__delitem__")
print("__iter__")
print("__next__")
print("__contains__")
print("__call__")
print("__eq__")
print("__ne__")
print("__lt__")
print("__gt__")
print("__le__")
print("__ge__")


print("      ")
print("rapidly assign values--------")
x, y, z = 1, 2, 3
print(x, y, z)
x = y = z = 10
print(x, y, z)
